package VRGenerator;

import ic2.api.item.Items;

import java.util.Arrays;

import net.minecraft.block.Block;
import net.minecraft.client.Minecraft;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid="VisibleRayGenerator", name="VisibleRayGenerator", version="build 4 (for mc1.6.4  ic22.0.336ex  Forge#965)", dependencies ="required-after:IC2")
@NetworkMod(clientSideRequired=true, serverSideRequired=false)
public class VisibleRayGenerator
{
	public static boolean isCE;

	public static int blockID_Solar;
	public static int blockID_artificialSun;
	public static int itemID_lavaUpdater;
	public static int LavaUpdateArea = 3;
	public static boolean isSolarCostUp;
//	public static boolean isICstacksizeUp;
	public static boolean isResistanceVanilla;
	public static Block solarBlock;
//	public static Block artificiaalSun;
	public static Item lavaUpdater;
	private CreativeTabs IcTab;
	
	public static int artificialSunGuiID = 0;
	public static final String TEXBlock = "/mods/CompactEngine/textures/blocks/";
	public static String texture = "/VRGenerator/texture/VRGenerator.png";
	public static String TexDomain = "vrgenerator:";
	@Instance("VisibleRayGenerator")
	public static VisibleRayGenerator instance;
	@SidedProxy(clientSide = "VRGenerator.ClientProxy", serverSide = "VRGenerator.CommonProxy")
	public static CommonProxy proxy;
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		setUpModInfo(event.getModMetadata());
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		config.load();
		blockID_Solar = config.get(Configuration.CATEGORY_BLOCK, "Solar ID", 175).getInt();
//		blockID_artificialSun = config.get(Configuration.CATEGORY_BLOCK, "VRGenerator ID", 1002).getInt();
		itemID_lavaUpdater = config.get(Configuration.CATEGORY_ITEM, "LavaUpdaterID", 4440).getInt();
//		LavaUpdateArea = config.get(Configuration.CATEGORY_GENERAL, "LavaUpdateArea", 4, "Effective range radius of Lava Updater. is set 4 = 9x9x9 min=1, max=63").getInt();
		isSolarCostUp = config.get(Configuration.CATEGORY_GENERAL, "isSolarCostUp", true, "Using a capacitor instead of a transformer recipe CE-Solar").getBoolean(true);
//		isICstacksizeUp = config.get(Configuration.CATEGORY_GENERAL, "isICstacksizeUp", true, "I will up the stacksize of IC2 some items").getBoolean(true);
		isResistanceVanilla = config.get(Configuration.CATEGORY_GENERAL, "isResistanceVanilla", true, "Set in the vanilla resistance of Obsidian, Water, Lava").getBoolean(true);
		config.save();
	}
	private void setUpModInfo(ModMetadata meta)
	{
		meta.authorList = Arrays.asList(new String[]{"takanasayo"});
		meta.autogenerated = true;
		meta.description = "Add some visible ray energy generator to mc152";
		meta.logoFile = "";
		meta.url = "http://forum.minecraftuser.jp/viewtopic.php?f=13&t=6672";
		meta.credits = "Updated By A.K.";
	}
	@EventHandler
	public void load(FMLInitializationEvent event)
	{
		NetworkRegistry.instance().registerGuiHandler(this, proxy);
		solarBlock = new CESolarBlock(blockID_Solar).setUnlocalizedName("CE_Solar");
		GameRegistry.registerBlock(solarBlock, CESolarItem.class, "visibleraysolor");
		lavaUpdater = new CEItemLavaUpdater(itemID_lavaUpdater).setUnlocalizedName(TexDomain + "CE_LavaUpdater").setTextureName(TexDomain + "CE_LavaUpdater");
		GameRegistry.registerItem(lavaUpdater, "lavaupdater");
		if(FMLCommonHandler.instance().getEffectiveSide().isClient()){
			getICTab();
		}
		solarBlock.setCreativeTab(IcTab);
		lavaUpdater.setCreativeTab(IcTab);
	}
	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		isCE = Loader.isModLoaded("CompactEngine");
		initIC();
		registerRecipesIC();
	}
	private void getICTab()
	{
		for(int i=0;i<CreativeTabs.creativeTabArray.length;i++)
		{
			if(CreativeTabs.creativeTabArray[i].getTabLabel() == "IC2")
			{
				IcTab = CreativeTabs.creativeTabArray[i];
			}
		}
	}
	public static void addChat(String message)
	{
		if(FMLCommonHandler.instance().getEffectiveSide().isClient())
		{
			Minecraft mc = Minecraft.getMinecraft();
			mc.ingameGUI.getChatGUI().printChatMessage(message);
		}
	}

	public static void addChat(String format,Object... args)
	{
		addChat(String.format(format,args));
	}
	
	public void initIC()
	{
		GameRegistry.registerTileEntity(CESolarTileEntity.class, "CE_Solar");
		GameRegistry.registerTileEntity(CEGeneratorTileEntity.class, "CE_Generator");
		
//		if(isICstacksizeUp)
//		{
//			VRGItemFieldAccessHelper.changeField(Items.getItem("energyCrystal").getItem(), 64);
//			VRGItemFieldAccessHelper.changeField(Items.getItem("lapotronCrystal").getItem(), 64);
//			VRGItemFieldAccessHelper.changeField(Items.getItem("treetap").getItem(), 64);
//			Items.getItem("reBattery").getItem().setMaxStackSize(64);
//			Items.getItem("coolingCell").getItem().setMaxStackSize(64);
//			Items.getItem("reinforcedDoorBlock").getItem().setMaxStackSize(64);
//		}
		
		if(isResistanceVanilla)
		{
			Block.obsidian.setResistance(2000F);
			Block.waterMoving.setResistance(500F);
			Block.waterStill.setResistance(500F);
			Block.lavaStill.setResistance(500F);
		}
	}
	private void registerRecipesIC()
	{
		ItemStack solar1 = new ItemStack(solarBlock, 1, 0);
		ItemStack solar2 = new ItemStack(solarBlock, 1, 1);
		ItemStack solar3 = new ItemStack(solarBlock, 1, 2);
		ItemStack solar4 = new ItemStack(solarBlock, 1, 3);
/*
		Item.lightStoneDust			//グロウストーンダスト
		Block.glowStone				//グロウストーン
		Block.glass					//ガラス
		Ic2Items.generator;			//地熱発電機
		Ic2Items.coalDust;			//石炭の粉
		Ic2Items.electronicCircuit;	//電子回路
		Ic2Items.advancedCircuit;	//発展回路
		Ic2Items.solarPanel;		//ソーラーパネル
		Ic2Items.batBox;
		Ic2Items.mfeUnit;
		Ic2Items.mfsUnit;
		Ic2Items.lvTransformer;		//低圧変圧器
		Ic2Items.mvTransformer;		//中圧変圧器
		Ic2Items.hvTransformer;		//高圧変圧器
		Ic2Items.energyCrystal;
		Ic2Items.lapotronCrystal;
		Ic2Items.reBattery;
		Ic2Items.treetap;
		Ic2Items.lavaCell;
		Ic2Items.carbonPlate;
		Ic2Items.coalChunk;
		Ic2Items.advancedAlloy;
		Ic2Items.iridiumPlate;
		Ic2Items.advancedMachine;
*/
		GameRegistry.addRecipe(new ItemStack(this.lavaUpdater), "c", "a", "i", 
				'c', Items.getItem("lavaCell"), 'a', Items.getItem("advancedCircuit"), 'i', Items.getItem("refinedIronIngot"));
		GameRegistry.addShapelessRecipe(solar1, Items.getItem("solarPanel"), Items.getItem("advancedCircuit"));
		if(isSolarCostUp)
		{
			GameRegistry.addRecipe(solar2, "sss", "sms", "sss", 's', solar1, 'm', Items.getItem("batBox"));
			GameRegistry.addRecipe(solar3, "sss", "sms", "sss", 's', solar2, 'm', Items.getItem("mfeUnit"));
			GameRegistry.addRecipe(solar4, "sss", "sms", "sss", 's', solar3, 'm', Items.getItem("mfsUnit"));
		}else{
			GameRegistry.addRecipe(solar2, "sss", "sms", "sss", 's', solar1, 'm', Items.getItem("lvTransformer"));
			GameRegistry.addRecipe(solar3, "sss", "sms", "sss", 's', solar2, 'm', Items.getItem("mvTransformer"));
			GameRegistry.addRecipe(solar4, "sss", "sms", "sss", 's', solar3, 'm', Items.getItem("hvTransformer"));
		}
		
		ItemStack[] rlg = new ItemStack[11];
		rlg[0] = solar1;
		for(int i = 0; i < 10; i++) rlg[i+1] = new ItemStack(solarBlock, 1, i+4);
		ItemStack[] items = {
			  new ItemStack(Block.glowStone) 
			, Items.getItem("electronicCircuit")
			, Items.getItem("advancedCircuit")
			, Items.getItem("lvTransformer")
			, Items.getItem("mvTransformer")
			, Items.getItem("hvTransformer")
			, Items.getItem("advancedMachine")
			, Items.getItem("advancedMachine")
			, Items.getItem("advancedMachine")
			, rlg[7]
			};
		ItemStack[] plates = {
				Items.getItem("carbonPlate")
			, Items.getItem("carbonPlate")
			, Items.getItem("carbonPlate")
			, Items.getItem("carbonPlate")
			, Items.getItem("carbonPlate")
			, Items.getItem("advancedAlloy")
			, Items.getItem("advancedAlloy")
			, Items.getItem("iridiumPlate")
			, Items.getItem("iridiumPlate")
			, Items.getItem("iridiumPlate")
			};
		
		GameRegistry.addRecipe(rlg[5], "psp","gmg","psp", 
			'p',Items.getItem("coalChunk"), 'g',solar4, 'm',Items.getItem("mvTransformer"), 's',Block.glowStone);
			
		for(int i = 0; i < 10; i++)
		{
			GameRegistry.addRecipe(rlg[i+1], "pgp","gmg","pgp", 'p',plates[i], 'g',rlg[i], 'm',items[i]);
		}
		

	}
}